import { ApiProperty } from '@nestjs/swagger';

export class ChatbotResponseDto {
    @ApiProperty({ description: 'Chatbot session ID', example: 1 })
    id: number;

    @ApiProperty({ description: 'Group ID', example: 1 })
    groupId: number;

    @ApiProperty({ description: 'Student ID', example: 1 })
    studentId: number;

    @ApiProperty({ description: 'Session creation date', example: '2024-01-01T00:00:00.000Z' })
    createdAt: Date;
}

export class ChatbotMessageResponseDto {
    @ApiProperty({ description: 'Message ID', example: 1 })
    id: number;

    @ApiProperty({ description: 'Message text', example: 'Hello, how can I help you?' })
    text: string;

    @ApiProperty({ description: 'Session ID', example: 1 })
    sessionId: number;

    @ApiProperty({ description: 'Whether the message was generated by AI', example: true })
    aiGenerated: boolean;

    @ApiProperty({ description: 'Message creation date', example: '2024-01-01T00:00:00.000Z' })
    createdAt: Date;
}

export class ChatbotWithMessagesResponseDto extends ChatbotResponseDto {
    @ApiProperty({
        description: 'Messages in the chatbot session',
        type: [ChatbotMessageResponseDto],
        example: [
            {
                id: 1,
                text: 'Hello, how can I help you?',
                sessionId: 1,
                aiGenerated: false,
                createdAt: '2024-01-01T00:00:00.000Z'
            },
            {
                id: 2,
                text: 'I can help you with your questions about the course material.',
                sessionId: 1,
                aiGenerated: true,
                createdAt: '2024-01-01T00:01:00.000Z'
            }
        ]
    })
    messages: ChatbotMessageResponseDto[];
}

export class SendMessageResponseDto {
    @ApiProperty({
        description: 'AI response message',
        example: 'I can help you with your questions about the course material. What would you like to know?'
    })
    answer: string;
}
